# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "gcloud" do |gcloud|
   gcloud.vm.box = "centos/7"
   gcloud.vm.hostname = "beta"
   gcloud.vm.box_check_update = false
   gcloud.vm.network "private_network", ip: "192.168.10.51", nic_type: "virtio", virtualbox__intnet: "deployment"
   
   gcloud.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.name = "gcloud"
      vb.memory = "512"
      vb.default_nic_type = "virtio"
   end
   
   gcloud.vm.provision "shell", path: "../script/init.sh"
   gcloud.vm.provision "shell", path: "../script/installGcloudSDK.sh"
   
  end
end
